### ISSUE TITLE
win10下无法设置五笔-拼音

### ISSUE THREAD

**Issue by ian-ie** [happyDom/dyyRime#1]

**Comment by ian-ie** [comment]
![图片](https://github.com/happyDom/dyyRime/assets/55068959/a74b6a2c-1fad-4e2b-b54f-2cb094a8ae04)
![图片](https://github.com/happyDom/dyyRime/assets/55068959/e49150fb-e472-4daf-ad69-fc977495f0f4)
![图片](https://github.com/happyDom/dyyRime/assets/55068959/2f9f26cf-350c-438f-97bd-fcb9fd1387c7)
f8可选，但是只能直接输入字母

**Comment by happyDom** [comment]
你好，你的问题解决了吗？
你的问题是因为没有 wubi_pinyin.schema.yaml 文档导致的，也就是说你没有安装 wubi_pinyin 输入方案。
在window环境下安装 wubi_pinyin 输入方案，请参考 https://blog.csdn.net/weixin_42148809/article/details/135224251 中相关章节。
![image](https://github.com/happyDom/dyyRime/assets/36214667/7031be4c-8001-48bb-a537-35687f5ec641)
