### ISSUE TITLE
五笔拼音如何只打首字母，就快打三、四字词？

### ISSUE THREAD

**Issue by ednykissyou** [happyDom/dyyRime#2]
五笔拼音如何只打首字母，就快打三、四字词？
小狼毫如何实现主词库已有单字拼音、单字五笔编码的基础上，再用扩展词库实现三四字词取首字母快打？

比如，我扩展里只有
魑魅魍魉
并没有注音，也没有编码，我如何只需输CMWL就可打出来

**Comment by happyDom** [comment]
一个想到的办法是可以使用lua将扩展库里的词组预处理成 CMWL：魑魅魍魉 这样的键值对，当你输入CMWL时，再将匹配的词组抛出，以实现这样的功能。
另一个方案是可以通过python将扩展里的词组预处理到 Custom_phrase.txt 中，本质还是进行了编码。只不过编码是根据主词库来自动生成的。
