### ISSUE TITLE
安装了五笔拼音后，打不出字

### ISSUE THREAD

**Issue by ThemanRonin** [happyDom/dyyRime#3]
安装了五笔拼音后，打不出字，一按就是些什么名词解释
![image](https://github.com/happyDom/dyyRime/assets/35099500/d8c3e620-9e29-4e7f-a962-8ab0fd11a402)

**Comment by happyDom** [comment]
亲，你需要先安装五笔・拼音输入方案，然后再使用本配置包。

你的问题是因为没有 wubi_pinyin.schema.yaml 文档导致的，也就是说你没有安装 wubi_pinyin 输入方案。
在window环境下安装 wubi_pinyin 输入方案，请参考 https://blog.csdn.net/weixin_42148809/article/details/135224251 中相关章节。
image
